-- Generated by Oracle SQL Developer Data Modeler 22.2.0.165.1149
--   at:        2022-11-25 19:28:07 PKT
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE


CREATE TABLE billing (
    invoice_number INTEGER NOT NULL,
    rate_per_hour  NUMBER(5) NOT NULL,
    total_cost     NUMBER(7) NOT NULL
)
LOGGING;

ALTER TABLE billing ADD CONSTRAINT billing_pk PRIMARY KEY ( invoice_number );

CREATE TABLE duration (
    "Date"                  DATE NOT NULL,
    start_time              DATE NOT NULL,
    end_time                DATE NOT NULL,
    no_of_reservation_hours INTEGER NOT NULL
)
LOGGING;

CREATE TABLE jobs (
    job_id    VARCHAR2(10) NOT NULL,
    job_title VARCHAR2(50 CHAR) NOT NULL,
    salary    INTEGER NOT NULL
)
LOGGING;

ALTER TABLE jobs ADD CONSTRAINT jobs_pk PRIMARY KEY ( job_id );

CREATE TABLE location (
    location_id INTEGER NOT NULL,
    address     VARCHAR2(150) NOT NULL,
    postal_code INTEGER NOT NULL,
    city        VARCHAR2(25) NOT NULL
)
LOGGING;

ALTER TABLE location ADD CONSTRAINT location_pk PRIMARY KEY ( location_id );

CREATE TABLE reservation (
    "Date"         DATE NOT NULL,
    start_time     DATE NOT NULL,
    invoice_number INTEGER NOT NULL,
    team_id        INTEGER NOT NULL,
    stadium_id     INTEGER NOT NULL
)
LOGGING;

ALTER TABLE reservation ADD CONSTRAINT reservation_pk PRIMARY KEY ( "Date",
                                                                    start_time );

CREATE TABLE seat (
    seat_type    VARCHAR2(15) NOT NULL,
    ticket_price NUMBER(5) NOT NULL
)
LOGGING;

ALTER TABLE seat ADD CONSTRAINT seat_pk PRIMARY KEY ( seat_type );

CREATE TABLE stadium (
    stadium_id       INTEGER NOT NULL,
    stadium_name     VARCHAR2(100) NOT NULL,
    stadium_type     VARCHAR2(20) NOT NULL,
    stadium_capacity INTEGER NOT NULL,
    address          VARCHAR2 
--  ERROR: VARCHAR2 size not specified 
     NOT NULL,
    location_id      INTEGER NOT NULL
)
LOGGING;

ALTER TABLE stadium ADD CONSTRAINT stadium_pk PRIMARY KEY ( stadium_id );

CREATE TABLE staff (
    staff_id     INTEGER NOT NULL,
    f_name       VARCHAR2(20 CHAR) NOT NULL,
    l_name       VARCHAR2(20 CHAR) NOT NULL,
    role         VARCHAR2 
--  ERROR: VARCHAR2 size not specified 
     NOT NULL,
    phone_number INTEGER NOT NULL,
    hire_date    DATE NOT NULL,
    job_id       VARCHAR2(10) NOT NULL
)
LOGGING;

COMMENT ON COLUMN staff.staff_id IS
    '	';

ALTER TABLE staff ADD CONSTRAINT staff_pk PRIMARY KEY ( staff_id );

CREATE TABLE team (
    team_id            INTEGER NOT NULL,
    team_name          VARCHAR2(50) NOT NULL,
    no_of_team_members INTEGER
)
LOGGING;

ALTER TABLE team ADD CONSTRAINT team_pk PRIMARY KEY ( team_id );

CREATE TABLE team_member (
    member_id    INTEGER NOT NULL,
    team_id      INTEGER NOT NULL,
    f_name       VARCHAR2(20) NOT NULL,
    l_name       VARCHAR2(20),
    age          INTEGER NOT NULL,
    phone_number INTEGER NOT NULL,
    sex          CHAR(1),
    role         VARCHAR2(25)
)
LOGGING;

ALTER TABLE team_member ADD CONSTRAINT team_member_pk PRIMARY KEY ( member_id );

CREATE TABLE ticket (
    ticket_id  INTEGER NOT NULL,
    "Date"     DATE NOT NULL,
    start_time DATE NOT NULL,
    stadium_id INTEGER NOT NULL,
    seat_type  VARCHAR2(15) NOT NULL
)
LOGGING;

ALTER TABLE ticket ADD CONSTRAINT ticket_pk PRIMARY KEY ( ticket_id );

ALTER TABLE duration
    ADD CONSTRAINT duration_reservation_fk FOREIGN KEY ( "Date",
                                                         start_time )
        REFERENCES reservation ( "Date",
                                 start_time )
    NOT DEFERRABLE;

ALTER TABLE reservation
    ADD CONSTRAINT reservation_billing_fk FOREIGN KEY ( invoice_number )
        REFERENCES billing ( invoice_number )
            ON UPDATE CASCADE ON DELETE CASCADE
    NOT DEFERRABLE;

ALTER TABLE reservation
    ADD CONSTRAINT reservation_stadium_fk FOREIGN KEY ( stadium_id )
        REFERENCES stadium ( stadium_id )
            ON UPDATE CASCADE ON DELETE CASCADE
    NOT DEFERRABLE;

ALTER TABLE reservation
    ADD CONSTRAINT reservation_team_fk FOREIGN KEY ( team_id )
        REFERENCES team ( team_id )
            ON UPDATE CASCADE ON DELETE CASCADE
    NOT DEFERRABLE;

ALTER TABLE stadium
    ADD CONSTRAINT stadium_location_fk FOREIGN KEY ( location_id )
        REFERENCES location ( location_id )
            ON UPDATE CASCADE ON DELETE CASCADE
    NOT DEFERRABLE;

ALTER TABLE staff
    ADD CONSTRAINT staff_jobs_fk FOREIGN KEY ( job_id )
        REFERENCES jobs ( job_id )
            ON UPDATE CASCADE ON DELETE CASCADE
    NOT DEFERRABLE;

ALTER TABLE team_member
    ADD CONSTRAINT team_member_team_fk FOREIGN KEY ( team_id )
        REFERENCES team ( team_id )
            ON UPDATE CASCADE ON DELETE CASCADE
    NOT DEFERRABLE;

ALTER TABLE ticket
    ADD CONSTRAINT ticket_seat_fk FOREIGN KEY ( seat_type )
        REFERENCES seat ( seat_type )
            ON UPDATE CASCADE ON DELETE CASCADE
    NOT DEFERRABLE;

ALTER TABLE ticket
    ADD CONSTRAINT ticket_stadium_fk FOREIGN KEY ( stadium_id )
        REFERENCES stadium ( stadium_id )
            ON UPDATE CASCADE ON DELETE CASCADE
    NOT DEFERRABLE;



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                            11
-- CREATE INDEX                             0
-- ALTER TABLE                             19
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   2
-- WARNINGS                                 0
