INSERT INTO LOCATION VALUES (1, 'National Stadium Colony, Gulshan-e-Iqbal', 74600, 'Karachi');
INSERT INTO LOCATION VALUES (2, 'Shahrah Noor Jahan, Block C North Nazimabad Town', 74700, 'Karachi');


INSERT INTO SEAT VALUES ('Lower', 500);
INSERT INTO SEAT VALUES ('Economy', 1000);
INSERT INTO SEAT VALUES ('First Class', 2000);

INSERT INTO STADIUM VALUES (1, 'National Stadium', 'Cricket', 34228, 1);
INSERT INTO STADIUM VALUES (2, 'Asghar Ali Shah Stadium', 'Cricket', 10000, 2);



INSERT INTO JOBS VALUES ('GDR', 'Gardener', 8000);
INSERT INTO TEAM VALUES (1, 'Abdul FC', 15);
INSERT INTO STAFF VALUES (1, 'Aamir', 'Bangee', 03331234567, '2022-11-22', 'GDR');
INSERT INTO TEAM_MEMBER values (1, 1, 'Abdullah', 'Naeem', 21, 03331236547, 'M', 'Owner');
INSERT INTO TICKET VALUES (1, '2022-11-22', '17:00:00', 2, 'First Class');
INSERT INTO BILLING VALUES (1, 1000, null, 1);
INSERT INTO RESERVATION VALUES ('2022-11-28', '18:00:00', 1, 1, 1);



SELECT STADIUM_NAME FROM LOCATION, STADIUM WHERE stadium.location_id = LOCATION.location_id; 
SELECT * FROM TEAM;
SELECT * FROM SEAT;
SELECT * FROM STADIUM;
SELECT * FROM JOBS;
SELECT * FROM LOCATION;
SELECT * FROM STAFF;
SELECT * FROM TEAM_MEMBER;
SELECT * FROM TICKET;
SELECT * FROM BILLING;
SELECT * FROM RESERVATION;