INSERT INTO LOCATION VALUES (1, 'National Stadium Colony, Gulshan-e-Iqbal', 74600, 'Karachi');
SELECT * FROM LOCATION;

INSERT INTO SEAT VALUES ('Lower', 500);
INSERT INTO SEAT VALUES ('Economy', 1000);
INSERT INTO SEAT VALUES ('First Class', 2000);

SELECT * FROM SEAT;

INSERT INTO STADIUM VALUES (1, 'National Stadium', 'Cricket', 34228, 1);

SELECT * FROM STADIUM;

SELECT STADIUM_NAME FROM LOCATION, STADIUM WHERE stadium.location_id = LOCATION.location_id; 

INSERT INTO JOBS VALUES ('GDR', 'Gardener', 8000);
SELECT * FROM JOBS;

UPDATE LOCATION SET location_id = 5 WHERE location_id = 1;


